name:                haskell-first-steps
version:             0.1.0.0
github:              "kuzznya/haskell-first-steps"
license:             MIT
author:              "Ilya Kuznetsov"
maintainer:          "ikuz2002@gmail.com"
copyright:           "2021 Ilya Kuznetsov"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/test-project#readme>

dependencies:
- base >= 4.7 && < 5
- random >= 1.1
- containers

library:
  source-dirs: src

executables:
  haskell-first-steps-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-first-steps

tests:
  haskell-first-steps-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-first-steps
